### ISSUE TITLE
[BUG] Unable to Fetch Pre-Season Testing Data (403 & 404 Errors)

### ISSUE THREAD

**Issue by foxyskippy** [theOehrly/Fast-F1#688]
### Describe the issue:

I'm trying to fetch Pre-Season Testing data for 2025 using fastf1.get_testing_session(), but the request fails due to 403 Forbidden and 404 Not Found errors when attempting to retrieve session data from livetiming.formula1.com and the FastF1 mirror.

### Reproduce the code example:

```python
import fastf1 as ff1
import logging

# Debug logging inschakelen
logging.basicConfig(level=logging.DEBUG)

### 💾 CACHE MODUS
ff1.Cache.enable_cache(r'F1 Telemetry')

### 📡 FASTF1 SESSION - TESTING DATA
session = ff1.get_testing_session(2025, 1, 1)
session.load()
preseasonlaps = session.laps

df = pd.DataFrame(preseasonlaps)
print(df)
```

### Error message:

```shell
Steps to Reproduce
Enable FastF1 caching:

import fastf1
fastf1.Cache.enable_cache('F1 Telemetry')
session = fastf1.get_testing_session(2025, 1, 1)
session.load()

Observed Behavior
FastF1 tries to retrieve data from:
https://livetiming.formula1.com/static/2025/2025-02-28_Pre-Season_Testing/2025-02-26_Practice_1/SessionInfo.jsonStream
but receives 403 Forbidden.
FastF1 then attempts the mirror:
https://livetiming-mirror.fastf1.dev/static/2025/2025-02-28_Pre-Season_Testing/2025-02-26_Practice_1/SessionInfo.jsonStream
which returns 404 Not Found.
Similar errors occur for driver data, timing data, telemetry, and weather information.
```

**Comment by ChemiF1** [comment]
There is no replay available at the F1 Oficial App. Has it any relation to the problem?

**Comment by Yoshi234** [comment]
I ran into the same issue while trying to fetch the testing data.

**Comment by RabbiNash** [comment]
Facing the same issue. If you get a fix please do help.

**Comment by pesaventofilippo** [comment]
@theOehrly I think they just changed the URL a bit:
From FastF1 3.4.4:

```
import fastf1
session = fastf1.get_testing_session(2025, 1, 1)
print(session.api_path) # '/static/2025/2025-02-28_Pre-Season_Testing/2025-02-26_Practice_1/'
```

But from `livetiming.formula1.com`:
`"Path": "2025/2025-02-28_Pre-Season_Testing/2025-02-26_Day_1/"`

Specifically, it's "Day_1" instead of the expected "Practice_1"

**Comment by theOehrly** [comment]
@pesaventofilippo i've got a few minutes right now... hacky fix incoming

**Comment by foxyskippy** [comment]
> [@theOehrly](https://github.com/theOehrly) I think they just changed the URL a bit: From FastF1 3.4.4:
> 
> ```
> import fastf1
> session = fastf1.get_testing_session(2025, 1, 1)
> print(session.api_path) # '/static/2025/2025-02-28_Pre-Season_Testing/2025-02-26_Practice_1/'
> ```
> 
> But from `livetiming.formula1.com`: `"Path": "2025/2025-02-28_Pre-Season_Testing/2025-02-26_Day_1/"`
> 
> Specifically, it's "Day_1" instead of the expected "Practice_1"

Yes @pesaventofilippo  you are correct

**Comment by theOehrly** [comment]
Should be working now. Please upgrade to v3.4.5. I hope it keeps working for the next two days as well, and that I didn't mess anything up.

**Comment by patadeganzo** [comment]
> Should be working now. Please upgrade to v3.4.5. I hope it keeps working for the next two days as well, and that I didn't mess anything up.

I upgraded the FastF1 library to version 3.4.5, but I’m still getting the same error. I’ve tried using "Pre-Season Testing" and "FP1" as inputs, as well as "Day_1" and "Practice_1," but the error keeps appearing. Any ideas on what might be causing this?

**Comment by pesaventofilippo** [comment]
@patadeganzo Are you using `get_testing_session()` instead of the normal `get_session()`?
For me it works now, using version 3.4.5 and `fastf1.get_testing_session(2025, 1, 1)`

**Comment by patadeganzo** [comment]
> [@patadeganzo](https://github.com/patadeganzo) Are you using `get_testing_session()` instead of the normal `get_session()`? For me it works now, using version 3.4.5 and `fastf1.get_testing_session(2025, 1, 1)`

It ran smoothly without any issues. It’s not the prettiest solution, but it gets the job done. Appreciate it, mate!

**Comment by Yoshi234** [comment]
@theOehrly thanks for the fix. It works now!
